spring:
  application:
    name: gateway-demo  # 应用名称
  cloud:
    gateway:
      enabled: true  # 启用 Spring Cloud Gateway
      routes:
        # 路径匹配规则，StripPrefix 过滤器会移除请求路径中的前缀
        - id: path_route  # 路由 ID
          predicates:
            - Path=/baidu  # 当请求路径匹配 /baidu 时应用此路由
          filters:
            - StripPrefix=1  # 移除请求路径中的第一个部分
          uri: https://www.bilibili.com  # 目标 URI

        # Cookie 匹配规则
        - id: cookie_route  # 路由 ID
          predicates:
            - Cookie=chocolate,ch.p  # 当请求包含名为 chocolate，值为 ch.p 的 Cookie 时应用此路由
          uri: https://www.google.com  # 目标 URI

        # 请求头匹配规则
        - id: header_route  # 路由 ID
          predicates:
            - Header=X-Request-Id, \d+  # 当请求头 X-Request-Id 匹配正则表达式 \d+ 时应用此路由
          uri: https://www.github.com  # 目标 URI

        # 组合匹配规则
        - id: compose  # 路由 ID
          predicates:
            - Path=/compose  # 当请求路径匹配 /compose 时应用此路由
            - Header=name, cong  # 且请求头 name 的值为 cong 时应用此路由
          uri: https://www.youtube.com  # 目标 URI
          filters:
            - StripPrefix=1  # 移除请求路径中的第一个部分

         # 示例服务路由
        - id: cloud-order-service
#          uri: lb://cloud-order-service  # 假设你有一个名为 cloud-order-service 的服务
          uri:  https://www.facebook.com/
          predicates:
            - Path=/order/**
            - After=2020-12-11T10:58:41.659+08:00[Asia/Taipei]
            - Before=2025-12-11T10:58:41.659+08:00[Asia/Taipei]
            - Between=2020-06-20T22:46:41.659+08:00[Asia/Taipei],2025-12-11T10:58:41.659+08:00[Asia/Taipei]
#            -After Before Between 如果同時使用要確認 Between 的時間要跟 After Before 一樣不然會無法匹配
            - Cookie=username,^\w+$
            - Header=username,^\w+$
            - Query=username, \d+
            - Query=password, \d+
            - Method=GET

    # sentinel看板相关配置
    sentinel:
      transport:
        dashboard: 127.0.0.1:8081
#      eager: true

